# Generated by Django 5.2.8 on 2025-12-01 22:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('IDOffre', models.AutoField(primary_key=True, serialize=False)),
                ('Organisme', models.CharField(max_length=100, verbose_name="Nom de l'organisme")),
                ('NomContact', models.CharField(max_length=100, verbose_name='Nom et prénom du contact')),
                ('EmailContact', models.EmailField(max_length=254, verbose_name='Email du contact')),
                ('Titre', models.CharField(max_length=100, verbose_name='Titre du stage')),
                ('Detail', models.TextField(verbose_name='Détail du stage')),
                ('DateDepot', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de dépôt')),
                ('Etat', models.CharField(choices=[('En attente', 'En attente validation'), ('Validée', 'Validée'), ('Refusée', 'Refusée'), ('Clôturée', 'Clôturée')], default='En attente', max_length=30)),
            ],
        ),
    ]
