# Generated by Django 5.2.8 on 2025-12-03 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_projet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('IDCandidature', models.AutoField(primary_key=True, serialize=False)),
                ('DateCandidature', models.DateTimeField(auto_now_add=True)),
                ('Etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship_projet.offre')),
            ],
            options={
                'unique_together': {('Offre', 'Etudiant')},
            },
        ),
    ]
