# Generated by Django 5.2.8 on 2025-12-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_projet', '0002_candidature'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='NbCandidats',
            field=models.IntegerField(default=0, verbose_name='Nombre de candidats actuels'),
        ),
    ]
